### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by wuxin008** [MangoFF/AI_Space_Ship#1]
I've tried every .py file, but i can't start this program.

**Comment by MangoFF** [comment]
May be you can try 'master' branch.

**Comment by wuxin008** [comment]
I am trying to use the master branch, but when running the MainWindow.py file, an error occurred. The error message is as follows:
Traceback (most recent call last):
  File "D:\program\python\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MainWindow.py", line 5, in <module>
    from plane import rungame,tech,AI_play,ship_labeling,train_model,remoeModel,removeData
  File "D:\jupyter\AIGame\AI_Space_Ship-master\AI_Space_Ship-master\plane.py", line 6, in <module>
    import pygame,random,sys,time   #sys模块中的exit用于退出
  File "D:\program\python\lib\site-packages\pygame\__init__.py", line 291, in <module>
    import pygame.pkgdata
  File "D:\program\python\lib\site-packages\pygame\pkgdata.py", line 25, in <module>
    from pkg_resources import resource_stream, resource_exists
  File "D:\program\python\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "D:\program\python\lib\site-packages\pkg_resources\extern\__init__.py", line 58, in create_module
    return self.load_module(spec.name)
  File "D:\program\python\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "D:\program\python\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "D:\program\python\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "D:\program\python\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "D:\program\python\lib\inspect.py", line 997, in getsource
    lines, lnum = getsourcelines(object)
  File "D:\program\python\lib\inspect.py", line 979, in getsourcelines
    lines, lnum = findsource(object)
  File "D:\program\python\lib\inspect.py", line 794, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "D:\program\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "D:\program\python\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "D:\program\python\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "D:\program\python\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "D:\program\python\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'D:\\program\\python\\lib\\site-packages\\win32\\pywintypes38.dll'

My python version is Python 3.8.8 and my operation system is windows10.
